### PR TITLE
Add the Curly talk proposal

### PR DESCRIPTION
**Pull request by dasch**
Hi guys! Trying this out. Please tell me if I've done something wrong.

### CODE REVIEW

**Comment by elle** [comment]
Hi Daniel,

I merged all the pull requests by mistake last night, so I reverted it all this morning.
Everything is fine with your proposal and you don't need to do anything. If your talk will be selected, I will merge your PR back into master.

Apologies for any inconvenience and thank you for your submission.
Elle

**Comment by dasch** [comment]
Hi @elle - no problem :-)

**Comment by dasch** [comment]
I don't need to make another PR?

**Comment by dasch** [comment]
@elle are you sure I don't need to reopen this PR?

**Comment by elle** [comment]
@dasch yes, I'm sure. I'm going to create a mini voting app in Sinatra.

**Comment by dasch** [comment]
Okay, thank you so much :-)

**Pull request merged**
